#! /usr/bin/python

"""Creates a completely random cow with the cowsay program.

Copyright (C) 2010  Nick Daly

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import random
import subprocess
import sys

MODES = list("bdgpstwy")
COWDIRS = os.getenv("COWPATH") or "/usr/share/cowsay/cows/"
FILES = []

cow_bin = "cowsay" if random.random() < 0.5 else "cowthink"
cow_mode = "" if random.random() < 0.5 else "-" + random.choice(MODES)
cow_file = ""

if random.random() > 0.5:
    for adir in COWDIRS.split(":"):
        FILES += os.listdir(adir)

    cow_file = "-f " + random.choice(FILES)

subprocess.call(
    ("%(cow_bin)s %(cow_mode)s %(cow_file)s" % locals()).split() + sys.argv[1:])
